#!/bin/bash

# Apache/Nginx log files locations
ERRLOG="/usr/local/nginx/logs/error.log"
ACCLOG="/usr/local/nginx/logs/access.log"

#### GTFO Config ####
# Install dir
WORKDIR="/usr/local/GTFO"
# List of banned IPs
BANNED="$WORKDIR/banned.ip"
# Number of lines to parse
LINES=100
# What to ban
KEYWORDS=("wp-login.php" "administrator/index.php" "../")
# Time to ban (hours)
HOURS=1
#####################

$IPTABLES="/sbin/iptables"

# Get current time
NOW=$(date +%Y%m%d%H%M)
DATE=$(date "+%Y-%m-%d %H:%M")

# Get current time minus $HOURS hours
XAGO=$(date --date="-$HOURS hours" +%Y%m%d%H%M)

echo "GTFO run - $DATE"

# Empty temp file 1
> $WORKDIR/tmp.1

# Find new suspicious IPs in error.log (using fgrep to avoid regex interpretation)
for K in ${KEYWORDS[@]}; do
  tail -n $LINES "$ERRLOG" | fgrep "$K" | sed -n 's/^.*client: //p' | cut -d',' -f1 | sort | uniq >> $WORKDIR/tmp.1
done

cut -d' ' -f1 $BANNED > $WORKDIR/tmp.2

# IPs to ban
BIPS=$(grep -v -f $WORKDIR/tmp.2 $WORKDIR/tmp.1)

# Number of IPs to ban
NBIPS=$(echo "$BIPS" | sed '/^$/d' | wc -l)

if [ "$NBIPS" -gt 0 ]; then
  echo "Banning the following IPs:"

  # Ban new suspicious IPs
  for IP in $BIPS; do
    echo "$IP"
    $IPTABLES -I INPUT 1 -s $IP -j DROP
  done

  # Save new IPs with banned time
  echo "$BIPS" | sed '/^$/d' | sed "s/\$/ $NOW/" >> $BANNED
fi

# Empty temp file 1
> $WORKDIR/tmp.1

echo "Checking for expired bans..."

# Unban expired IPs
cat $WORKDIR/banned.ip | while read LINE; do
  L=($LINE)
  DATE=${L[1]}
  # If $DATE is older than $XAGO, time to unban this IP
  if [ "$XAGO" -ge "$DATE" ]; then
    # Unban current IP
    IP=${L[0]}
    echo "$IP"
    # Add unbanned IP to temp file
    echo "$IP" >> $WORKDIR/tmp.1
    $IPTABLES -D INPUT -s $IP -j DROP
  fi
done

# Update banned IPs (remove unbanned)
grep -v -f $WORKDIR/tmp.1 $BANNED > $WORKDIR/tmp.2
cp $WORKDIR/tmp.2 $BANNED

# Clean temp files
rm $WORKDIR/tmp.1
rm $WORKDIR/tmp.2

